In [ ]:
# import numpy as np
# 1 D array
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

# zero D array 
arr1 = np.array(42)
print(arr1)

# 2 D array 
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print("-------------")
# 3 D array
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)

In [8]:
# checking the dimention 

arr = np.array(42)
arr1 = np.array([1,2,3,4,5])

print(arr.ndim)
print(arr1.ndim)

# defining the Dimentions 

arr2 = np.array([1,2,3,4,5], ndmin = 5)
print(arr2.ndim)

0
1
5


In [11]:
#Accessing array
#1D

arr1 = np.array([1,2,3,4])
print(arr1[1])

#2D array 

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[0,2])

#3D array

arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3[0,1,1])

2
3
5


In [13]:
#array slicing 

arr = np.array([1,2,3,4,5])
arr1 = arr[1:4]
print(arr1)

#slicing 2 D array 

arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr3 = arr2[1, 1:3]
print(arr3)

[2 3 4]
[6 7]


In [14]:
# Checking the Data type of array element 
arr = np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [17]:
#Creating array with defined data type
arr = np.array([1,2,3,4], dtype = 'i4')
print(arr.dtype)

int32


In [20]:
# Converrting Data Type for existing array 
''' To do this we can use methon named astype() this creates a copy of existing array and allow to use new data type '''

arr = np.array([1,2,3,4,5])
print(arr.dtype)

arr1 = arr.astype('S')
print(arr1.dtype)
print(arr1)

int32
|S11
[b'1' b'2' b'3' b'4' b'5']


In [21]:
# changig array to boolean 

arr = np.array([1,2,0,0,1,3])
print(arr.dtype)

arr1 = arr.astype(bool)
print(arr1.dtype)
print(arr1)

int32
bool
[ True  True False False  True  True]


In [22]:
# Difference Between copy and view 
''' The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.'''

# COPY 

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0]=23

print(arr)
print(x)




[23  2  3  4  5]
[1 2 3 4 5]
